# Generated by Django 5.2 on 2025-05-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('teacher_id', models.CharField(max_length=20, unique=True)),
                ('teacher_email', models.EmailField(max_length=20)),
                ('address', models.TextField()),
                ('Deparment', models.CharField(max_length=100)),
                ('Specialization', models.CharField(max_length=100)),
                ('Experience_years', models.CharField(max_length=10)),
                ('Qualification', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('joining_date', models.DateField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('teacher_image', models.ImageField(blank=True, upload_to='teachers/')),
                ('is_Active', models.BooleanField(default=True)),
            ],
        ),
    ]
