# Generated by Django 5.2 on 2025-05-01 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Deparment',
            new_name='Department',
        ),
    ]
