# Generated by Django 5.2 on 2025-05-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_rename_deparment_teacher_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Experience_years',
            new_name='experience_years',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='is_Active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Qualification',
            new_name='qualification',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Specialization',
            new_name='specialization',
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='joining_date',
            field=models.DateField(null=True),
        ),
    ]
