# Generated by Django 5.2 on 2025-05-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_teacher_experience_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_email',
            field=models.EmailField(max_length=20, null=True),
        ),
    ]
