# Generated by Django 5.2 on 2025-05-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='department',
            name='department_head',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='head_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
