# Generated by Django 5.2 on 2025-05-04 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_contact_number_department_department_head_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='department.department')),
            ],
        ),
    ]
