# Generated by Django 5.2 on 2025-05-08 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_department_contact_number_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
